# Generated by Django 4.2.2 on 2023-07-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_aluno_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
